language: php
php:
- '5.5'
deploy:
  provider: gae
  keyfile: client-secret.json
  project: bill-hahn-sandbox
before_install:
- openssl aes-256-cbc -K $encrypted_c08febd5f850_key -iv $encrypted_c08febd5f850_iv
  -in client-secret.json.enc -out client-secret.json -d
