runtime: php55
api_version: 1
service: autocomplete-php

handlers:
- url: /.*
  script: index.php

env_variables:
  MYSQL_HOST: '35.184.135.20'
  MYSQL_DB: 'prodcat'
  MYSQL_USER: 'root'
  MYSQL_PW: 'gcp2@cloud'
