runtime: php55
api_version: 1
service: autocomplete-usa

handlers:

- url: /.*
  script: index.php

- url: /.*
  script: data.php
  
- url: /(.+\.php)$
  script: \1

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PW: 'gcp2@cloud'
  MYSQL_DB: 'prodcat'
  MYSQL_SOCKET: '/cloudsql/bill-hahn-sandbox:us-central1:myinstance'
  
#beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
#  cloud_sql_instances: bill-hahn-sandbox:us-central1:myinstance

#- url: /.*
#  script: data-hardcoded.php
#
#- url: /.*
#  script: index.php
#
#- url: /(.+\.php)$
#  script: \1